### ISSUE TITLE
Rebuild errors - missing files and directory

### ISSUE THREAD

**Issue by abhishek2desh** [NullTerminatorr/NullBase#4]
https://www.awesomescreenshot.com/image/3862577/ab790987390219e1085850b425f2a6ee

Missing some files please add them to the source.

**Comment by abhishek2desh** [comment]
okay the only issue is d3dx9.h file missing. help.

**Comment by ghost** [comment]
Download DirectX 9 and add it to the "Include Directories" and "Library Directories" in Project>Properties>Configuration Properties>VC++ Directories

**(or you could google the problem maybe)**

https://www.microsoft.com/en-us/download/details.aspx?id=8109 
https://www.google.com/search?q=directx+9+june+2010
